# ----- Estágio 1: Build (Construção) -----
FROM maven:3.8.5-openjdk-21-slim AS build

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de configuração do Maven

COPY .mvn/ .mvn
COPY mvnw .
COPY pom.xml .

# Baixa as dependências
RUN mvn dependency:go-offline

# Agora copia o código-fonte
COPY src src

# Constrói o projeto, gera o .jar e pula os testes (para um build mais rápido)
RUN mvn package -DskipTests


# ----- Estágio 2: Run (Execução) -----
# Use uma imagem JRE (Runtime) slim, que é muito menor
FROM openjdk:21-jre-slim

# Define o diretório de trabalho
WORKDIR /app

# Expõe a porta que o Spring usa (padrão 8080)
EXPOSE 8080

# Copia APENAS o .jar do estágio de build para esta nova imagem
# A pasta de destino do Maven é /app/target/
COPY --from=build /app/target/*.jar app.jar

# Comando para rodar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]